name: CI

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
    branches:
      - "**"

  pull_request:
    branches:
      - "**:**"

  release:

jobs:
  build:
    runs-on: ubuntu-24.04
    if: contains('refs/heads/main', github.ref) || startsWith(github.ref, 'refs/heads/release') || startsWith(github.ref, 'refs/heads/preview') || startsWith(github.ref, 'refs/tags/')

    steps:
      - uses: actions/checkout@v4
      - name: Build image & push to Docker Hub
        env:
          DOCKER_REPOSITORY: manastech/redirect-to-prefix
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
        run: ./.github/build.sh
